group: thunderllm-benchmark-pretrained
task:
  # english - for Pretrained Model Evaluation
  - thunderllm-hellaswag
  - thunderllm-winogrande
  - thunderllm-openbookqa
  - thunderllm-arc_easy
  - thunderllm-arc_challenge
  - thunderllm-mmlu


  # korean - for Pretrained Model Evaluation
  - thunderllm-snu-ko-arc-easy
  - thunderllm-snu-ko-arc-challenge
  - thunderllm-snu-ko-winogrande
  - thunderllm-snu-ko-lambada
  - thunderllm-kobest_hellaswag
  - thunderllm-kmmlu

